export * from './accounts.service';
import { AccountsApiService } from './accounts.service';
export * from './assignments.service';
import { AssignmentsApiService } from './assignments.service';
export * from './auth.service';
import { AuthApiService } from './auth.service';
export * from './clients.service';
import { ClientsApiService } from './clients.service';
export * from './dashboard.service';
import { DashboardApiService } from './dashboard.service';
export * from './gameSKUs.service';
import { GameSKUsApiService } from './gameSKUs.service';
export * from './games.service';
import { GamesApiService } from './games.service';
export * from './loyaltyPoints.service';
import { LoyaltyPointsApiService } from './loyaltyPoints.service';
export * from './notifications.service';
import { NotificationsApiService } from './notifications.service';
export * from './orders.service';
import { OrdersApiService } from './orders.service';
export * from './profiles.service';
import { ProfilesApiService } from './profiles.service';
export * from './reservations.service';
import { ReservationsApiService } from './reservations.service';
export * from './services.service';
import { ServicesApiService } from './services.service';
export * from './subscriptions.service';
import { SubscriptionsApiService } from './subscriptions.service';
export * from './vendors.service';
import { VendorsApiService } from './vendors.service';
export * from './vendorsPublic.service';
import { VendorsPublicApiService } from './vendorsPublic.service';
export const APIS = [AccountsApiService, AssignmentsApiService, AuthApiService, ClientsApiService, DashboardApiService, GameSKUsApiService, GamesApiService, LoyaltyPointsApiService, NotificationsApiService, OrdersApiService, ProfilesApiService, ReservationsApiService, ServicesApiService, SubscriptionsApiService, VendorsApiService, VendorsPublicApiService];
