// Generated by Wrangler by running `wrangler types`
interface Env {
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_CHAT_ID: string;
	SUPABASE_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	RESEND_API_KEY?: string;
	SENDER_EMAIL?: string;
	REPLY_TO_EMAIL?: string;
	CRON_SECRET?: string;
}
