# Memory
shared_buffers = 1GB
effective_cache_size = 2GB
work_mem = 8MB
maintenance_work_mem = 256MB

# Connections
max_connections = 50

# WAL PITR
max_wal_size = 1GB
min_wal_size = 80MB
checkpoint_completion_target = 0.9

# Logging
log_min_duration_statement = 500