syntax = "proto3";

package neversion.notification;

option java_multiple_files = true;
option java_package = "com.neversion.api.notification.infrastructure.adapters.out.grpc";

service NotificationService {
    rpc SendNotification (NotificationRequest) returns (NotificationResponse);
    rpc CheckExists (CheckExistsRequest) returns (CheckExistsResponse);
}

message NotificationRequest {
    string event_type = 1;      // CLIENT_WELCOME, SUBSCRIPTION_RENEWED, etc.
    string recipient = 2;       // Recipient email or destination
    string payload = 3;         // JSON stringified payload
    string reference_type = 4;  // subscription, client, etc.
    int64 reference_id = 5;     // Resource internal database ID
    string tags = 6;            // welcome, renew, revoked, etc.
}

message NotificationResponse {
    bool success = 1;
    string message = 2;
    string notification_uuid = 3;
}

message CheckExistsRequest {
    string reference_type = 1;
    int64 reference_id = 2;
    string tags = 3;
}

message CheckExistsResponse {
    bool exists = 1;
}
