/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountProfitMarginResult { 
    accountUuid?: string;
    email?: string;
    serviceName?: string;
    saleMode?: string;
    accountCost?: number;
    maxProfiles?: number;
    profilesSold?: number;
    newRevenue?: number;
    renewalRevenue?: number;
    totalRevenue?: number;
    totalDiscount?: number;
    allocatedCost?: number;
    profit?: number;
    marginPct?: number;
}

