/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountWithSubscriptionRequest { 
    email?: string;
    password?: string;
    serviceUuid: string;
    saleMode?: string;
    renewalDate: string;
    plan?: string;
    cost?: number;
    source?: string;
    purchasedAt?: string;
    accountNotes?: string;
    maxProfiles?: number;
    clientUuid: string;
    paymentDueDate: string;
    priceSold?: number;
    discountApplied?: number;
    subscriptionNotes?: string;
    sendNotification?: boolean;
}

