/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileSummaryResponse } from './profileSummaryResponse';
import { AccountResponse } from './accountResponse';
import { AccountSummaryResponse } from './accountSummaryResponse';


export interface AccountDetailResponse { 
    account?: AccountResponse;
    profiles?: Array<ProfileSummaryResponse>;
    summary?: AccountSummaryResponse;
}

