/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountResponse { 
    id?: string;
    email?: string;
    password?: string;
    serviceId?: number;
    saleMode?: AccountResponse.SaleModeEnum;
    status?: AccountResponse.StatusEnum;
    renewalDate?: string;
    plan?: string;
    cost?: number;
    source?: string;
    purchasedAt?: string;
    notes?: string;
    createdAt?: string;
    totalProfiles?: number;
    availableProfiles?: number;
    occupiedProfiles?: number;
    blockedProfiles?: number;
}
export namespace AccountResponse {
    export const SaleModeEnum = {
        ByProfile: 'BY_PROFILE',
        FullAccount: 'FULL_ACCOUNT'
    } as const;
    export type SaleModeEnum = typeof SaleModeEnum[keyof typeof SaleModeEnum];
    export const StatusEnum = {
        Available: 'AVAILABLE',
        Partial: 'PARTIAL',
        Full: 'FULL',
        Expired: 'EXPIRED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


