/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountRequest { 
    email?: string;
    pass?: string;
    serviceId: string;
    saleMode: AccountRequest.SaleModeEnum;
    renewalDate: string;
    plan?: string;
    cost: number;
    source?: string;
    purchasedAt?: string;
    notes?: string;
    maxProfiles?: number;
}
export namespace AccountRequest {
    export const SaleModeEnum = {
        ByProfile: 'BY_PROFILE',
        FullAccount: 'FULL_ACCOUNT'
    } as const;
    export type SaleModeEnum = typeof SaleModeEnum[keyof typeof SaleModeEnum];
}


