/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountGroupResult { 
    accountId?: string;
    email?: string;
    password?: string;
    cutOffDate?: string;
    accountType?: string;
    accountStatus?: string;
    maxProfiles?: number;
    occupiedProfiles?: number;
    availableProfiles?: number;
    availability?: string;
}

