/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BatchItemResult { 
    serviceId?: string;
    status?: BatchItemResult.StatusEnum;
    subscriptionId?: string;
    errorMessage?: string;
}
export namespace BatchItemResult {
    export const StatusEnum = {
        Success: 'SUCCESS',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


