/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BatchItem } from './batchItem';


export interface BatchCreateManualSubscriptionRequest { 
    clientId: string;
    items?: Array<BatchItem>;
    discountApplied: number;
    paymentDueDate: string;
    notes?: string;
    sendNotification?: boolean;
}

