/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Service line shown in the authenticated client\'s order history.
 */
export interface ClientOrderServiceResponse { 
    serviceId?: string;
    serviceName?: string;
    quantity?: number;
}

