/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderSummary } from './orderSummary';
import { ActiveSubscriptionSummary } from './activeSubscriptionSummary';
import { Client } from './client';


export interface ClientDetail { 
    client?: Client;
    activeSubscriptions?: Array<ActiveSubscriptionSummary>;
    orderHistory?: Array<OrderSummary>;
}

