/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientAccessResponse { 
    subscriptionId?: string;
    serviceName?: string;
    accountEmail?: string;
    accountPassword?: string;
    profileName?: string;
    profilePin?: string;
    paymentDueDate?: string;
    status?: string;
}

