/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientOrderServiceResponse } from './clientOrderServiceResponse';


/**
 * Reservation and receipt status visible to the authenticated client.
 */
export interface ClientReservationStatusResponse { 
    id?: string;
    status?: string;
    total?: number;
    discount?: number;
    receiptUrl?: string;
    paymentMethod?: string;
    expirationDate?: string;
    createdAt?: string;
    notes?: string;
    renewalSubscriptionId?: string;
    services?: Array<ClientOrderServiceResponse>;
}

