/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientOrderServiceResponse } from './clientOrderServiceResponse';


/**
 * Order history row for the authenticated client.
 */
export interface ClientOrderHistoryResponse { 
    id?: string;
    reservationId?: string;
    status?: string;
    paymentMethod?: string;
    total?: number;
    discount?: number;
    receiptUrl?: string;
    approvedAt?: string;
    createdAt?: string;
    services?: Array<ClientOrderServiceResponse>;
}

