/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Client { 
    id?: number;
    uuid?: string;
    userId?: number;
    vendorId?: number;
    name?: string;
    phone?: string;
    email?: string;
    notes?: string;
    createdAt?: string;
}

