/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfirmAssignmentResponse { 
    subscriptionId?: string;
    orderId?: string;
    profileId?: string;
    clientId?: string;
    serviceName?: string;
    startDate?: string;
    endDate?: string;
    notificationQueued?: boolean;
}

