/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CurrentUserResponse { 
    /**
     * Public UUID of the internal platform user
     */
    userUuid?: string;
    /**
     * External Supabase subject linked to the platform user
     */
    externalId?: string;
    /**
     * Platform role in lowercase
     */
    role?: string;
    /**
     * Public UUID of the vendor record when the caller is a vendor
     */
    vendorUuid?: string;
    /**
     * Vendor store display name when the caller is a vendor
     */
    storeName?: string;
}

