/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExpiringAccountResult { 
    accountId?: string;
    serviceName?: string;
    accountEmail?: string;
    renewalDate?: string;
    status?: string;
}

