/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FinancialSnapshot { 
    serviceId?: string;
    serviceName?: string;
    priceSold?: number;
    discountApplied?: number;
    saleMode?: FinancialSnapshot.SaleModeEnum;
}
export namespace FinancialSnapshot {
    export const SaleModeEnum = {
        ByProfile: 'BY_PROFILE',
        FullAccount: 'FULL_ACCOUNT'
    } as const;
    export type SaleModeEnum = typeof SaleModeEnum[keyof typeof SaleModeEnum];
}


