/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameRequest { 
    /**
     * Game name, e.g. Free Fire
     */
    name?: string;
    /**
     * URL-friendly slug, unique per vendor
     */
    slug?: string;
    /**
     * Optional URL to the game logo/image
     */
    imageUrl?: string;
}

