/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameRequest { 
    /**
     * Game identifier code, e.g. ff-100
     */
    code?: string;
    /**
     * Game name, e.g. Free Fire 100 Diamonds
     */
    name?: string;
    /**
     * Price of the game item
     */
    price: number;
    /**
     * Optional URL to the game logo/image
     */
    imageUrl?: string;
}

