/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameResponse { 
    /**
     * Public UUID of the game
     */
    id?: string;
    /**
     * Game identifier code
     */
    code?: string;
    /**
     * Game name
     */
    name?: string;
    /**
     * Price of the game item
     */
    price?: number;
    /**
     * URL to the game logo/image
     */
    imageUrl?: string;
    /**
     * Whether the game is active and visible in the store
     */
    isActive?: boolean;
    /**
     * Creation timestamp
     */
    createdAt?: string;
}

