/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameSkuResponse { 
    /**
     * Public UUID of the game SKU
     */
    id?: string;
    /**
     * SKU identifier code
     */
    code?: string;
    /**
     * SKU name
     */
    name?: string;
    /**
     * Price of the SKU
     */
    price?: number;
    /**
     * URL to the SKU image
     */
    imageUrl?: string;
    /**
     * Whether the SKU is active and visible in the store
     */
    isActive?: boolean;
    /**
     * UUID of the parent game
     */
    gameUuid?: string;
    /**
     * Slug of the parent game (filled by service)
     */
    gameSlug?: string;
    /**
     * Name of the parent game (filled by service)
     */
    gameName?: string;
    /**
     * Creation timestamp
     */
    createdAt?: string;
}

