/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameSkuRequest { 
    /**
     * SKU identifier code, e.g. ff-110
     */
    code?: string;
    /**
     * SKU name, e.g. Free Fire 110 Diamonds
     */
    name?: string;
    /**
     * Price of the SKU
     */
    price: number;
    /**
     * Optional URL to the SKU image
     */
    imageUrl?: string;
    /**
     * UUID of the parent game this SKU belongs to
     */
    gameUuid?: string;
}

