/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReservationResponse } from './reservationResponse';
import { StatusChangeResponse } from './statusChangeResponse';


export interface OrderDetailResponse { 
    id?: string;
    reservationId?: string;
    status?: OrderDetailResponse.StatusEnum;
    paymentMethod?: string;
    total?: number;
    discount?: number;
    notes?: string;
    receiptUrl?: string;
    approvedAt?: string;
    createdAt?: string;
    reservation?: ReservationResponse;
    statusHistory?: Array<StatusChangeResponse>;
}
export namespace OrderDetailResponse {
    export const StatusEnum = {
        Validated: 'VALIDATED',
        Completed: 'COMPLETED',
        Rejected: 'REJECTED',
        Cancelled: 'CANCELLED',
        Pending: 'PENDING'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


