/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderResponse { 
    id?: string;
    reservationId?: string;
    status?: OrderResponse.StatusEnum;
    paymentMethod?: string;
    total?: number;
    discount?: number;
    notes?: string;
    receiptUrl?: string;
    approvedAt?: string;
    createdAt?: string;
}
export namespace OrderResponse {
    export const StatusEnum = {
        Validated: 'VALIDATED',
        Completed: 'COMPLETED',
        Rejected: 'REJECTED',
        Cancelled: 'CANCELLED',
        Pending: 'PENDING'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


