/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PointsMovementResponse { 
    id?: string;
    entryType?: PointsMovementResponse.EntryTypeEnum;
    status?: PointsMovementResponse.StatusEnum;
    points?: number;
    notes?: string;
    createdAt?: string;
}
export namespace PointsMovementResponse {
    export const EntryTypeEnum = {
        Earn: 'EARN',
        Redeem: 'REDEEM',
        Adjustment: 'ADJUSTMENT',
        Reversal: 'REVERSAL'
    } as const;
    export type EntryTypeEnum = typeof EntryTypeEnum[keyof typeof EntryTypeEnum];
    export const StatusEnum = {
        Available: 'AVAILABLE',
        Pending: 'PENDING',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


