/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProfileResponse { 
    id?: string;
    accountId?: number;
    name?: string;
    pin?: string;
    isOwner?: boolean;
    createdAt?: string;
}

