/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileCustomerResult } from './profileCustomerResult';


export interface ProfileSubscriptionResult { 
    subscriptionId?: string;
    startDate?: string;
    endDate?: string;
    status?: string;
    customer?: ProfileCustomerResult;
}

