/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProfileResponse { 
    id?: string;
    accountId?: number;
    name?: string;
    pin?: string;
    notes?: string;
    isOwner?: boolean;
    status?: ProfileResponse.StatusEnum;
    createdAt?: string;
}
export namespace ProfileResponse {
    export const StatusEnum = {
        Available: 'AVAILABLE',
        Active: 'ACTIVE',
        Reserved: 'RESERVED',
        Occupied: 'OCCUPIED',
        Blocked: 'BLOCKED',
        Expired: 'EXPIRED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


