/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfileSubscriptionResult } from './profileSubscriptionResult';


export interface ProfileResult { 
    profileId?: string;
    profileName?: string;
    pin?: string;
    profileStatus?: string;
    subscription?: ProfileSubscriptionResult;
}

