/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterVendorRequest { 
    /**
     * Vendor\'s email address
     */
    email?: string;
    /**
     * Display name for the vendor\'s storefront
     */
    storeName?: string;
    /**
     * Optional URL to the vendor\'s logo
     */
    logoUrl?: string;
    /**
     * Optional JSON with bank/payment details
     */
    bankDetails?: string;
    /**
     * Optional JSON with discount tier configuration (BR-13)
     */
    discountCfg?: string;
}

