/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterClientRequest { 
    /**
     * Client\'s email address
     */
    email?: string;
    /**
     * Client\'s chosen password (required for standard registration)
     */
    password?: string;
    /**
     * Client\'s display name
     */
    name?: string;
    /**
     * Required phone number — used to link existing manual clients
     */
    phone?: string;
    /**
     * UUID of the vendor (store) to register with
     */
    vendorUuid: string;
    /**
     * Optional external auth user ID from Supabase (required for OAuth)
     */
    externalId?: string;
}

