/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterClientResponse { 
    /**
     * External Supabase subject linked to the platform user
     */
    externalId?: string;
    /**
     * Public UUID of the created client record
     */
    clientUuid?: string;
    /**
     * Client\'s display name
     */
    name?: string;
    /**
     * Client\'s email address
     */
    email?: string;
}

