/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterVendorResponse { 
    /**
     * External Supabase subject linked to the platform user
     */
    externalId?: string;
    /**
     * Public UUID of the created vendor record
     */
    vendorUuid?: string;
    /**
     * Vendor\'s store display name
     */
    storeName?: string;
    /**
     * Vendor\'s email address
     */
    email?: string;
}

