/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReservationDetailResponse } from './reservationDetailResponse';


export interface ReservationResponse { 
    id?: string;
    clientId?: string;
    clientName?: string;
    clientEmail?: string;
    status?: ReservationResponse.StatusEnum;
    discount?: number;
    total?: number;
    receiptUrl?: string;
    paymentMethod?: string;
    accountPreference?: ReservationResponse.AccountPreferenceEnum;
    expirationDate?: string;
    createdAt?: string;
    renewalSubscriptionId?: string;
    details?: Array<ReservationDetailResponse>;
    pointsRedeemed?: number;
    pointsDiscount?: number;
}
export namespace ReservationResponse {
    export const StatusEnum = {
        Pending: 'PENDING',
        Uploaded: 'UPLOADED',
        Validated: 'VALIDATED',
        Rejected: 'REJECTED',
        Expired: 'EXPIRED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const AccountPreferenceEnum = {
        CuentaNueva: 'CUENTA_NUEVA',
        CuentaPropia: 'CUENTA_PROPIA'
    } as const;
    export type AccountPreferenceEnum = typeof AccountPreferenceEnum[keyof typeof AccountPreferenceEnum];
}


