/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReservationItemRequest } from './reservationItemRequest';


export interface ReservationRequest { 
    clientId: string;
    items: Array<ReservationItemRequest>;
    paymentMethod?: string;
    accountPreference?: ReservationRequest.AccountPreferenceEnum;
    notes?: string;
}
export namespace ReservationRequest {
    export const AccountPreferenceEnum = {
        CuentaNueva: 'CUENTA_NUEVA',
        CuentaPropia: 'CUENTA_PROPIA'
    } as const;
    export type AccountPreferenceEnum = typeof AccountPreferenceEnum[keyof typeof AccountPreferenceEnum];
}


