/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReservationDetailResponse { 
    uuid?: string;
    serviceId?: number;
    qty?: number;
    unitPrice?: number;
    subtotal?: number;
}

