/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceResponse { 
    id?: string;
    name?: string;
    maxProfiles?: number;
    details?: string;
    category?: ServiceResponse.CategoryEnum;
    createdAt?: string;
}
export namespace ServiceResponse {
    export const CategoryEnum = {
        Streaming: 'STREAMING',
        Software: 'SOFTWARE',
        GiftCard: 'GIFT_CARD',
        Recharge: 'RECHARGE',
        DigitalService: 'DIGITAL_SERVICE'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
}


