/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceProfitSummaryResult { 
    serviceName?: string;
    activeAccounts?: number;
    totalProfilesSold?: number;
    totalRevenue?: number;
    totalAllocatedCost?: number;
    totalProfit?: number;
    avgMarginPct?: number;
}

