/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceResponse { 
    /**
     * Public UUID of the service
     */
    id?: string;
    /**
     * Service name
     */
    name?: string;
    /**
     * Service category
     */
    category?: ServiceResponse.CategoryEnum;
    /**
     * Service description
     */
    description?: string;
    /**
     * URL to the service logo/image
     */
    imageUrl?: string;
    /**
     * Price per individual profile sale
     */
    priceProfile?: number;
    /**
     * Price for full account sale (Cuenta Completa)
     */
    priceComplete?: number;
    /**
     * Subscription duration in days
     */
    durationDays?: number;
    /**
     * Maximum profiles allowed per account
     */
    maxProfiles?: number;
    /**
     * Whether the service is active and visible in the store
     */
    isActive?: boolean;
    /**
     * Free-form JSON metadata
     */
    details?: string;
    /**
     * Creation timestamp
     */
    createdAt?: string;
}
export namespace ServiceResponse {
    export const CategoryEnum = {
        Streaming: 'streaming',
        DigitalService: 'digital_service'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
}


