/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatusChangeResponse { 
    oldStatus?: StatusChangeResponse.OldStatusEnum;
    newStatus?: StatusChangeResponse.NewStatusEnum;
    changedBy?: string;
    notes?: string;
    changedAt?: string;
}
export namespace StatusChangeResponse {
    export const OldStatusEnum = {
        Validated: 'VALIDATED',
        Completed: 'COMPLETED',
        Rejected: 'REJECTED',
        Cancelled: 'CANCELLED',
        Pending: 'PENDING'
    } as const;
    export type OldStatusEnum = typeof OldStatusEnum[keyof typeof OldStatusEnum];
    export const NewStatusEnum = {
        Validated: 'VALIDATED',
        Completed: 'COMPLETED',
        Rejected: 'REJECTED',
        Cancelled: 'CANCELLED',
        Pending: 'PENDING'
    } as const;
    export type NewStatusEnum = typeof NewStatusEnum[keyof typeof NewStatusEnum];
}


