/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountSummary } from './accountSummary';
import { FinancialSnapshot } from './financialSnapshot';
import { AccessSummary } from './accessSummary';
import { OrderSummary } from './orderSummary';
import { ClientSummary } from './clientSummary';
import { ProfileSummary } from './profileSummary';


export interface SubscriptionDetailResponse { 
    id?: string;
    status?: SubscriptionDetailResponse.StatusEnum;
    startDate?: string;
    endDate?: string;
    paymentDueDate?: string;
    monthsPaid?: number;
    notes?: string;
    createdAt?: string;
    financialSnapshot?: FinancialSnapshot;
    client?: ClientSummary;
    profile?: ProfileSummary;
    account?: AccountSummary;
    access?: AccessSummary;
    order?: OrderSummary;
}
export namespace SubscriptionDetailResponse {
    export const StatusEnum = {
        Active: 'ACTIVE',
        Pending: 'PENDING',
        Suspended: 'SUSPENDED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


