/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SuggestAssignmentResponse { 
    hasSuggestion?: boolean;
    saleMode?: SuggestAssignmentResponse.SaleModeEnum;
    suggestedProfileId?: string;
    suggestedAccountId?: string;
    serviceName?: string;
    accountEmail?: string;
    noInventoryReason?: string;
}
export namespace SuggestAssignmentResponse {
    export const SaleModeEnum = {
        ByProfile: 'BY_PROFILE',
        FullAccount: 'FULL_ACCOUNT'
    } as const;
    export type SaleModeEnum = typeof SaleModeEnum[keyof typeof SaleModeEnum];
}


