/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VendorPublicResponse { 
    /**
     * Public UUID of the vendor — used for multi-tenant API calls
     */
    id?: string;
    /**
     * Display name of the vendor\'s store
     */
    storeName?: string;
    /**
     * URL to the vendor\'s logo image
     */
    logoUrl?: string;
    /**
     * Discount tier configuration as JSON (BR-13). Used by the storefront to calculate dynamic combo discounts.
     */
    discountCfg?: string;
}

