/**
 * Neversion Panel API
 *
 * Contact: support@neversion.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VendorProfileResponse { 
    /**
     * Public UUID of the vendor
     */
    id?: string;
    /**
     * Display name of the vendor\'s store
     */
    storeName?: string;
    /**
     * URL to the vendor\'s logo image
     */
    logoUrl?: string;
    /**
     * Bank details JSON string
     */
    bankDetails?: string;
    /**
     * Discount tier configuration JSON string
     */
    discountCfg?: string;
    /**
     * Rewards configuration JSON string
     */
    rewardsCfg?: string;
    /**
     * Creation timestamp
     */
    createdAt?: string;
}

